export const sampleData = [
  {
    type: "task order",
    name: "TO1",
    Summary: "TO1",
    Progress: 0.4958,
    level: 0,
    id: 1,
    portfolioEpics: [
      {
        type: "portfolio epic",
        plannedStart: "NaN/NaN/NaN",
        plannedEnd: "NaN/NaN/NaN",
        Key: "KEY5123",
        Summary: "PortFolio Epic 1",
        "Component/s": "C1, C2, C3",
        Labels: "FY24Q1, FY24Q2",
        Progress: 0.75,
        "Issue Type": "Portfolio Epic",
        level: 1,
        id: 2,
        capabilities: [
          {
            type: "capability",
            name: "Capability 1",
            plannedStart: "1/10/2024",
            plannedEnd: "4/4/2024",
            labels: ["FY24Q2"],
            Key: "KEY5134",
            Summary: "Capability 1",
            "Planned Start": 45302,
            "Planned End": 45387,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q2",
            Progress: 0.8,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 3,
            epics: [],
          },
          {
            type: "capability",
            name: "Capability 2",
            plannedStart: "1/10/2024",
            plannedEnd: "6/19/2024",
            labels: ["FY24Q2"],
            Key: "KEY5376",
            Summary: "Capability 2",
            "Planned Start": 45302,
            "Planned End": 45463,
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
            Labels: "FY24Q2, Refine",
            Progress: 1,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 70,
            epics: [],
          },
          {
            type: "capability",
            name: "Capability 3",
            plannedStart: "1/10/2024",
            plannedEnd: "4/10/2024",
            labels: ["FY24Q1", "FY24Q2"],
            Key: "KEY5188",
            Summary: "Capability 3",
            "Planned Start": 45302,
            "Planned End": 45393,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q1, FY24Q2",
            Progress: 1,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 71,
            epics: [
              {
                type: "epic",
                Key: "KEY5189",
                Summary: "Deduplication Software Testing Cleanup",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 72,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5274",
                Summary: "Deduplication Software Cleanup & Enhancements",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 86,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 4",
            plannedStart: "4/11/2024",
            plannedEnd: "5/7/2024",
            labels: ["FY24Q4"],
            Key: "KEY7897",
            Summary: "Capability 4",
            "Planned Start": 45394,
            "Planned End": 45420,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q4",
            Progress: 0.2,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 116,
            epics: [
              {
                type: "epic",
                Key: "KEY7902",
                Summary:
                  "Text Comparison Summary Tab and Similarity Percentage Challenges",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Progress: 0.2,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 117,
                stories: [],
              },
            ],
          },
        ],
      },
      {
        type: "portfolio epic",
        plannedStart: "NaN/NaN/NaN",
        plannedEnd: "NaN/NaN/NaN",
        Key: "KEY5326",
        Summary: "Modernization Support",
        "Component/s": "C1, C2, C3",
        Labels: "FY24Q2, FY24Q3",
        Progress: 0.2417,
        "Issue Type": "Portfolio Epic",
        level: 1,
        id: 123,
        capabilities: [
          {
            type: "capability",
            name: "Capability 5",
            plannedStart: "1/10/2024",
            plannedEnd: "4/10/2024",
            labels: ["FY24Q2"],
            Key: "KEY5327",
            Summary: "Capability 5",
            "Planned Start": 45302,
            "Planned End": 45393,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q2",
            Progress: 0.6667,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 124,
            epics: [
              {
                type: "epic",
                Key: "KEY3670",
                Summary:
                  "PRD - Develop and Deliver Product Requirements Document",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 125,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5365",
                Summary: "AoA - Analysis of Alternatives",
                "Planned Start": 45302,
                "Planned End": 45329,
                "Component/s": "DM&E, TO3",
                Labels: "FY24Q2",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 126,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5366",
                Summary:
                  "Modernization roadmap and minimum viable product (MVP)",
                "Planned Start": 45323,
                "Planned End": 45371,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 127,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 6",
            plannedStart: "4/11/2024",
            plannedEnd: "7/2/2024",
            labels: ["FY24Q3"],
            Key: "KEY5328",
            Summary: "Capability 6",
            "Planned Start": 45394,
            "Planned End": 45476,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0.375,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 130,
            epics: [
              {
                type: "epic",
                Key: "KEY7933",
                Summary: "Installation of Beinformed on A5 cloud",
                "Planned Start": 45394,
                "Planned End": 45406,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q3, Modernization_Planning",
                Progress: 0.75,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 131,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8246",
                Summary: "HCD tasks for modernization",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, HCD, TO3",
                Labels: "FY24Q3, Unplanned",
                Progress: 0.5,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 136,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7932",
                Summary: "BeInformed  Scope & Training",
                "Planned Start": 45394,
                "Planned End": 45406,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q3, Modernization_Planning",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 139,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7934",
                Summary:
                  "Model Driven Usage-Delivery Pipeline Scope & Training",
                "Component/s": "C1, C2, C3",
                Labels: "HCD, Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 141,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7935",
                Summary: "Model Development POC",
                "Planned Start": 45421,
                "Planned End": 45476,
                "Component/s": "C1, C2, C3",
                Labels: "Dev, FY24Q3, HCD, Modernization_Planning",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 142,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7936",
                Summary: "Model Updates, Additions, O&M",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 143,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 7",
            plannedStart: "5/8/2024",
            plannedEnd: "7/2/2024",
            labels: [],
            Key: "KEY5348",
            Summary: "Capability 7",
            "Planned Start": 45421,
            "Planned End": 45476,
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
            Progress: 0,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 144,
            epics: [
              {
                type: "epic",
                Key: "KEY5367",
                Summary: "Project Plan for the MVP",
                "Planned Start": 45323,
                "Planned End": 45371,
                "Component/s": "DM&E, PB, TO3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 145,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5368",
                Summary: "Modernization Communications Materials",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, PB, TO3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 146,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 8",
            plannedStart: "NaN/NaN/NaN",
            plannedEnd: "NaN/NaN/NaN",
            labels: ["FY24Q3"],
            Key: "KEY7946",
            Summary: "Capability 8",
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 147,
            epics: [
              {
                type: "epic",
                Key: "KEY7948",
                Summary: "Data Orchestration Requirements",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 148,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7949",
                Summary: "Data Orchestration Research",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 149,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7952",
                Summary: "Data Orchestration API Implementation",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 150,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7953",
                Summary: "Data Orchestration MVP Build Testing",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 151,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 9",
            plannedStart: "NaN/NaN/NaN",
            plannedEnd: "NaN/NaN/NaN",
            labels: ["FY24Q3"],
            Key: "KEY7937",
            Summary: "Capability 9",
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0.1667,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 152,
            epics: [
              {
                type: "epic",
                Key: "KEY7938",
                Summary: "Data Lake Discovery, Training, & Design",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 153,
                stories: [
                  {
                    type: "story",
                    Key: "KEY8155",
                    Summary:
                      "Spike: Research Data Lake best practices and helpful courses",
                    "Component/s": "C1, C2, C3",
                    Progress: 1,
                    "Issue Type": "Story",
                    level: 4,
                    hidden: true,
                    id: 154,
                  },
                ],
              },
              {
                type: "epic",
                Key: "KEY7941",
                Summary: "Data Lake MVP Sample/Test Data Load",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 155,
                stories: [
                  {
                    type: "story",
                    Key: "KEY8153",
                    Summary: "Spike: Visualization of FDMS/Documentum data",
                    "Component/s": "C1, C2, C3",
                    Progress: 0,
                    "Issue Type": "Story",
                    level: 4,
                    hidden: true,
                    id: 156,
                  },
                ],
              },
              {
                type: "epic",
                Key: "KEY7939",
                Summary: "Data Lake MVP implementation",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 157,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7942",
                Summary: "Data Lake MVP Performance Testing",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 158,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8470",
                Summary: "Structure of Docket, Document, Comment",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
                Labels: "FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 159,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8471",
                Summary: "Data Architecture within Comment Analysis",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
                Labels: "FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 165,
                stories: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "task order",
    name: "TO2",
    Summary: "TO2",
    Progress: 0.4958,
    level: 0,
    id: 1,
    portfolioEpics: [
      {
        type: "portfolio epic",
        plannedStart: "NaN/NaN/NaN",
        plannedEnd: "NaN/NaN/NaN",
        Key: "KEY5123",
        Summary: "PortFolio Epic 1",
        "Component/s": "C1, C2, C3",
        Labels: "FY24Q1, FY24Q2",
        Progress: 0.75,
        "Issue Type": "Portfolio Epic",
        level: 1,
        id: 2,
        capabilities: [
          {
            type: "capability",
            name: "Capability 1",
            plannedStart: "1/10/2024",
            plannedEnd: "4/4/2024",
            labels: ["FY24Q2"],
            Key: "KEY5134",
            Summary: "Capability 1",
            "Planned Start": 45302,
            "Planned End": 45387,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q2",
            Progress: 0.8,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 3,
            epics: [],
          },
          {
            type: "capability",
            name: "Capability 2",
            plannedStart: "1/10/2024",
            plannedEnd: "6/19/2024",
            labels: ["FY24Q2"],
            Key: "KEY5376",
            Summary: "Capability 2",
            "Planned Start": 45302,
            "Planned End": 45463,
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
            Labels: "FY24Q2, Refine",
            Progress: 1,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 70,
            epics: [],
          },
          {
            type: "capability",
            name: "Capability 3",
            plannedStart: "1/10/2024",
            plannedEnd: "4/10/2024",
            labels: ["FY24Q1", "FY24Q2"],
            Key: "KEY5188",
            Summary: "Capability 3",
            "Planned Start": 45302,
            "Planned End": 45393,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q1, FY24Q2",
            Progress: 1,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 71,
            epics: [
              {
                type: "epic",
                Key: "KEY5189",
                Summary: "Deduplication Software Testing Cleanup",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 72,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5274",
                Summary: "Deduplication Software Cleanup & Enhancements",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 86,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 4",
            plannedStart: "4/11/2024",
            plannedEnd: "5/7/2024",
            labels: ["FY24Q4"],
            Key: "KEY7897",
            Summary: "Capability 4",
            "Planned Start": 45394,
            "Planned End": 45420,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q4",
            Progress: 0.2,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 116,
            epics: [
              {
                type: "epic",
                Key: "KEY7902",
                Summary:
                  "Text Comparison Summary Tab and Similarity Percentage Challenges",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Progress: 0.2,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 117,
                stories: [],
              },
            ],
          },
        ],
      },
      {
        type: "portfolio epic",
        plannedStart: "NaN/NaN/NaN",
        plannedEnd: "NaN/NaN/NaN",
        Key: "KEY5326",
        Summary: "Modernization Support",
        "Component/s": "C1, C2, C3",
        Labels: "FY24Q2, FY24Q3",
        Progress: 0.2417,
        "Issue Type": "Portfolio Epic",
        level: 1,
        id: 123,
        capabilities: [
          {
            type: "capability",
            name: "Capability 5",
            plannedStart: "1/10/2024",
            plannedEnd: "4/10/2024",
            labels: ["FY24Q2"],
            Key: "KEY5327",
            Summary: "Capability 5",
            "Planned Start": 45302,
            "Planned End": 45393,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q2",
            Progress: 0.6667,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 124,
            epics: [
              {
                type: "epic",
                Key: "KEY3670",
                Summary:
                  "PRD - Develop and Deliver Product Requirements Document",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 125,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5365",
                Summary: "AoA - Analysis of Alternatives",
                "Planned Start": 45302,
                "Planned End": 45329,
                "Component/s": "DM&E, TO3",
                Labels: "FY24Q2",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 126,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5366",
                Summary:
                  "Modernization roadmap and minimum viable product (MVP)",
                "Planned Start": 45323,
                "Planned End": 45371,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 127,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 6",
            plannedStart: "4/11/2024",
            plannedEnd: "7/2/2024",
            labels: ["FY24Q3"],
            Key: "KEY5328",
            Summary: "Capability 6",
            "Planned Start": 45394,
            "Planned End": 45476,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0.375,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 130,
            epics: [
              {
                type: "epic",
                Key: "KEY7933",
                Summary: "Installation of Beinformed on A5 cloud",
                "Planned Start": 45394,
                "Planned End": 45406,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q3, Modernization_Planning",
                Progress: 0.75,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 131,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8246",
                Summary: "HCD tasks for modernization",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, HCD, TO3",
                Labels: "FY24Q3, Unplanned",
                Progress: 0.5,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 136,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7932",
                Summary: "BeInformed  Scope & Training",
                "Planned Start": 45394,
                "Planned End": 45406,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q3, Modernization_Planning",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 139,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7934",
                Summary:
                  "Model Driven Usage-Delivery Pipeline Scope & Training",
                "Component/s": "C1, C2, C3",
                Labels: "HCD, Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 141,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7935",
                Summary: "Model Development POC",
                "Planned Start": 45421,
                "Planned End": 45476,
                "Component/s": "C1, C2, C3",
                Labels: "Dev, FY24Q3, HCD, Modernization_Planning",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 142,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7936",
                Summary: "Model Updates, Additions, O&M",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 143,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 7",
            plannedStart: "5/8/2024",
            plannedEnd: "7/2/2024",
            labels: [],
            Key: "KEY5348",
            Summary: "Capability 7",
            "Planned Start": 45421,
            "Planned End": 45476,
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
            Progress: 0,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 144,
            epics: [
              {
                type: "epic",
                Key: "KEY5367",
                Summary: "Project Plan for the MVP",
                "Planned Start": 45323,
                "Planned End": 45371,
                "Component/s": "DM&E, PB, TO3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 145,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5368",
                Summary: "Modernization Communications Materials",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, PB, TO3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 146,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 8",
            plannedStart: "NaN/NaN/NaN",
            plannedEnd: "NaN/NaN/NaN",
            labels: ["FY24Q3"],
            Key: "KEY7946",
            Summary: "Capability 8",
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 147,
            epics: [
              {
                type: "epic",
                Key: "KEY7948",
                Summary: "Data Orchestration Requirements",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 148,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7949",
                Summary: "Data Orchestration Research",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 149,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7952",
                Summary: "Data Orchestration API Implementation",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 150,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7953",
                Summary: "Data Orchestration MVP Build Testing",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 151,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 9",
            plannedStart: "NaN/NaN/NaN",
            plannedEnd: "NaN/NaN/NaN",
            labels: ["FY24Q3"],
            Key: "KEY7937",
            Summary: "Capability 9",
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0.1667,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 152,
            epics: [
              {
                type: "epic",
                Key: "KEY7938",
                Summary: "Data Lake Discovery, Training, & Design",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 153,
                stories: [
                  {
                    type: "story",
                    Key: "KEY8155",
                    Summary:
                      "Spike: Research Data Lake best practices and helpful courses",
                    "Component/s": "C1, C2, C3",
                    Progress: 1,
                    "Issue Type": "Story",
                    level: 4,
                    hidden: true,
                    id: 154,
                  },
                ],
              },
              {
                type: "epic",
                Key: "KEY7941",
                Summary: "Data Lake MVP Sample/Test Data Load",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 155,
                stories: [
                  {
                    type: "story",
                    Key: "KEY8153",
                    Summary: "Spike: Visualization of FDMS/Documentum data",
                    "Component/s": "C1, C2, C3",
                    Progress: 0,
                    "Issue Type": "Story",
                    level: 4,
                    hidden: true,
                    id: 156,
                  },
                ],
              },
              {
                type: "epic",
                Key: "KEY7939",
                Summary: "Data Lake MVP implementation",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 157,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7942",
                Summary: "Data Lake MVP Performance Testing",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 158,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8470",
                Summary: "Structure of Docket, Document, Comment",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
                Labels: "FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 159,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8471",
                Summary: "Data Architecture within Comment Analysis",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
                Labels: "FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 165,
                stories: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "task order",
    name: "TO3",
    Summary: "TO3",
    Progress: 0.4958,
    level: 0,
    id: 1,
    portfolioEpics: [
      {
        type: "portfolio epic",
        plannedStart: "NaN/NaN/NaN",
        plannedEnd: "NaN/NaN/NaN",
        Key: "KEY5123",
        Summary: "PortFolio Epic 1",
        "Component/s": "C1, C2, C3",
        Labels: "FY24Q1, FY24Q2",
        Progress: 0.75,
        "Issue Type": "Portfolio Epic",
        level: 1,
        id: 2,
        capabilities: [
          {
            type: "capability",
            name: "Capability 1",
            plannedStart: "1/10/2024",
            plannedEnd: "4/4/2024",
            labels: ["FY24Q2"],
            Key: "KEY5134",
            Summary: "Capability 1",
            "Planned Start": 45302,
            "Planned End": 45387,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q2",
            Progress: 0.8,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 3,
            epics: [],
          },
          {
            type: "capability",
            name: "Capability 2",
            plannedStart: "1/10/2024",
            plannedEnd: "6/19/2024",
            labels: ["FY24Q2"],
            Key: "KEY5376",
            Summary: "Capability 2",
            "Planned Start": 45302,
            "Planned End": 45463,
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
            Labels: "FY24Q2, Refine",
            Progress: 1,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 70,
            epics: [],
          },
          {
            type: "capability",
            name: "Capability 3",
            plannedStart: "1/10/2024",
            plannedEnd: "4/10/2024",
            labels: ["FY24Q1", "FY24Q2"],
            Key: "KEY5188",
            Summary: "Capability 3",
            "Planned Start": 45302,
            "Planned End": 45393,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q1, FY24Q2",
            Progress: 1,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 71,
            epics: [
              {
                type: "epic",
                Key: "KEY5189",
                Summary: "Deduplication Software Testing Cleanup",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 72,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5274",
                Summary: "Deduplication Software Cleanup & Enhancements",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 86,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 4",
            plannedStart: "4/11/2024",
            plannedEnd: "5/7/2024",
            labels: ["FY24Q4"],
            Key: "KEY7897",
            Summary: "Capability 4",
            "Planned Start": 45394,
            "Planned End": 45420,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q4",
            Progress: 0.2,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 116,
            epics: [
              {
                type: "epic",
                Key: "KEY7902",
                Summary:
                  "Text Comparison Summary Tab and Similarity Percentage Challenges",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
                Progress: 0.2,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 117,
                stories: [],
              },
            ],
          },
        ],
      },
      {
        type: "portfolio epic",
        plannedStart: "NaN/NaN/NaN",
        plannedEnd: "NaN/NaN/NaN",
        Key: "KEY5326",
        Summary: "Modernization Support",
        "Component/s": "C1, C2, C3",
        Labels: "FY24Q2, FY24Q3",
        Progress: 0.2417,
        "Issue Type": "Portfolio Epic",
        level: 1,
        id: 123,
        capabilities: [
          {
            type: "capability",
            name: "Capability 5",
            plannedStart: "1/10/2024",
            plannedEnd: "4/10/2024",
            labels: ["FY24Q2"],
            Key: "KEY5327",
            Summary: "Capability 5",
            "Planned Start": 45302,
            "Planned End": 45393,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q2",
            Progress: 0.6667,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 124,
            epics: [
              {
                type: "epic",
                Key: "KEY3670",
                Summary:
                  "PRD - Develop and Deliver Product Requirements Document",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 125,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5365",
                Summary: "AoA - Analysis of Alternatives",
                "Planned Start": 45302,
                "Planned End": 45329,
                "Component/s": "DM&E, TO3",
                Labels: "FY24Q2",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 126,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5366",
                Summary:
                  "Modernization roadmap and minimum viable product (MVP)",
                "Planned Start": 45323,
                "Planned End": 45371,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q2",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 127,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 6",
            plannedStart: "4/11/2024",
            plannedEnd: "7/2/2024",
            labels: ["FY24Q3"],
            Key: "KEY5328",
            Summary: "Capability 6",
            "Planned Start": 45394,
            "Planned End": 45476,
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0.375,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 130,
            epics: [
              {
                type: "epic",
                Key: "KEY7933",
                Summary: "Installation of Beinformed on A5 cloud",
                "Planned Start": 45394,
                "Planned End": 45406,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q3, Modernization_Planning",
                Progress: 0.75,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 131,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8246",
                Summary: "HCD tasks for modernization",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, HCD, TO3",
                Labels: "FY24Q3, Unplanned",
                Progress: 0.5,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 136,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7932",
                Summary: "BeInformed  Scope & Training",
                "Planned Start": 45394,
                "Planned End": 45406,
                "Component/s": "C1, C2, C3",
                Labels: "FY24Q3, Modernization_Planning",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 139,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7934",
                Summary:
                  "Model Driven Usage-Delivery Pipeline Scope & Training",
                "Component/s": "C1, C2, C3",
                Labels: "HCD, Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 141,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7935",
                Summary: "Model Development POC",
                "Planned Start": 45421,
                "Planned End": 45476,
                "Component/s": "C1, C2, C3",
                Labels: "Dev, FY24Q3, HCD, Modernization_Planning",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 142,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7936",
                Summary: "Model Updates, Additions, O&M",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 143,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 7",
            plannedStart: "5/8/2024",
            plannedEnd: "7/2/2024",
            labels: [],
            Key: "KEY5348",
            Summary: "Capability 7",
            "Planned Start": 45421,
            "Planned End": 45476,
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, PB, TO3",
            Progress: 0,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 144,
            epics: [
              {
                type: "epic",
                Key: "KEY5367",
                Summary: "Project Plan for the MVP",
                "Planned Start": 45323,
                "Planned End": 45371,
                "Component/s": "DM&E, PB, TO3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 145,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY5368",
                Summary: "Modernization Communications Materials",
                "Planned Start": 45302,
                "Planned End": 45371,
                "Component/s": "DM&E, PB, TO3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 146,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 8",
            plannedStart: "NaN/NaN/NaN",
            plannedEnd: "NaN/NaN/NaN",
            labels: ["FY24Q3"],
            Key: "KEY7946",
            Summary: "Capability 8",
            "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 147,
            epics: [
              {
                type: "epic",
                Key: "KEY7948",
                Summary: "Data Orchestration Requirements",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 148,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7949",
                Summary: "Data Orchestration Research",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 149,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7952",
                Summary: "Data Orchestration API Implementation",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 150,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7953",
                Summary: "Data Orchestration MVP Build Testing",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 151,
                stories: [],
              },
            ],
          },
          {
            type: "capability",
            name: "Capability 9",
            plannedStart: "NaN/NaN/NaN",
            plannedEnd: "NaN/NaN/NaN",
            labels: ["FY24Q3"],
            Key: "KEY7937",
            Summary: "Capability 9",
            "Component/s": "C1, C2, C3",
            Labels: "FY24Q3, Modernization_Planning",
            Progress: 0.1667,
            "Issue Type": "Capability",
            level: 2,
            hidden: true,
            id: 152,
            epics: [
              {
                type: "epic",
                Key: "KEY7938",
                Summary: "Data Lake Discovery, Training, & Design",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 1,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 153,
                stories: [
                  {
                    type: "story",
                    Key: "KEY8155",
                    Summary:
                      "Spike: Research Data Lake best practices and helpful courses",
                    "Component/s": "C1, C2, C3",
                    Progress: 1,
                    "Issue Type": "Story",
                    level: 4,
                    hidden: true,
                    id: 154,
                  },
                ],
              },
              {
                type: "epic",
                Key: "KEY7941",
                Summary: "Data Lake MVP Sample/Test Data Load",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 155,
                stories: [
                  {
                    type: "story",
                    Key: "KEY8153",
                    Summary: "Spike: Visualization of FDMS/Documentum data",
                    "Component/s": "C1, C2, C3",
                    Progress: 0,
                    "Issue Type": "Story",
                    level: 4,
                    hidden: true,
                    id: 156,
                  },
                ],
              },
              {
                type: "epic",
                Key: "KEY7939",
                Summary: "Data Lake MVP implementation",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 157,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY7942",
                Summary: "Data Lake MVP Performance Testing",
                "Component/s": "C1, C2, C3",
                Labels: "Modernization_Planning, Potential_FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 158,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8470",
                Summary: "Structure of Docket, Document, Comment",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
                Labels: "FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 159,
                stories: [],
              },
              {
                type: "epic",
                Key: "KEY8471",
                Summary: "Data Architecture within Comment Analysis",
                "Component/s": "DM&E, ERM O&M/DM&E SW Team, SB, TO3",
                Labels: "FY24Q3",
                Progress: 0,
                "Issue Type": "Epic",
                level: 3,
                hidden: true,
                id: 165,
                stories: [],
              },
            ],
          },
        ],
      },
    ],
  }
];
